server:
  service:
    type: NodePort
    nodePort: 30001  # Set a NodePort to access Prometheus externally

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 7d  # Retain data for 7

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'nginx-exporter'
        scrape_interval: 15s
        static_configs:
          - targets: ['nginx-exporter-prometheus-nginx-exporter.monitoring.svc.cluster.local:9113']

      - job_name: 'node-exporter'
        scrape_interval: 15s
        static_configs:
          - targets: ['prometheus-prometheus-node-exporter.monitoring.svc.cluster.local:9100']

      - job_name: 'kube-state-metrics'
        scrape_interval: 15s
        static_configs:
          - targets: ['prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080']
