apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
  labels:
    app: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push  # Update with the correct Loki service endpoint
    scrape_configs:
      - job_name: nginx-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: nginx_log
              __path__: /var/log/nginx/access.log  # NGINX log 

      - job_name: error-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: error_log
              __path__: /var/log/nginx/error.log  # NGINX log
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
              
            - name: nginx-logs
              mountPath: /var/log/nginx  # Same mount path as NGINX logs
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: nginx-logs
          hostPath:
              path: /home/ubuntu/nginx-logs  # Path on the host to mount
              type: Directory
